### ISSUE TITLE
Insecure self signed certificates

### ISSUE THREAD

**Issue by danielloader** [Tantalor93/dnspyre#77]
Would it possible to add an insecure flag to ignore self signed certificates? 
Load testing on an internal environment with ephemeral DNS clusters would benefit greatly from being able to accept an untrusted certificate.

Thanks

**Comment by Tantalor93** [comment]
Hello! Thanks for opening this issue, i guess this is related both to DoH and DoT?

**Comment by danielloader** [comment]
Yeah ideally both. If the implementation of DoT is more effort than insecure DoH would be helpful enough.

Thanks for the reply.

**Comment by Tantalor93** [comment]
I have added the `--insecure` flag, it should be available from version `2.4.0` . The option should be usable by both DoT and DoH benchmarks, let me know if you encounter any other problems or have some other features in mind, thanks!

**Comment by danielloader** [comment]
Thank you so much, I'll try it Monday at work.

**Comment by danielloader** [comment]
Works! Thank you very much.
